### ISSUE TITLE
Prepare works for contributing to ShardingSphere

### ISSUE THREAD

**Issue by KomachiSion** [avalon566/sharding-scaling#2]
There are some based function and prepare works before contributing to ShardingSphere.

- [x] Add Apache License
- [x] Remove or replace illegal dependences
    - [x] Remove mysql-connector-java jar
    - [x] Remove mysql-binlog-connector-java jar [sharding-scaling#3](https://github.com/avalon566/sharding-scaling/issues/3)
- [x] MySQL support
    - [x] Connect Channel to MySQL
    - [x] Parse binlog event  [sharding-scaling#3](https://github.com/avalon566/sharding-scaling/issues/3)
- [x] ~~PostgreSQL support~~ (implement after merge)
- [x] ~~Integrate with ShardingSphere~~ (implement after merge)
    - [x] ~~Change to a Service process~~ (implement after merge)
    - [x] ~~Provide API to generate or stop migrate jobs~~ (implement after merge)
- [x] CheckStyle
- [x] Operation document

If some other works need to be done or some works can be done after contributing, please discuss in comment

reference:

1.  [apache/incubator-shardingsphere#3077](https://github.com/apache/incubator-shardingsphere/issues/3077)
2.  [apache/incubator-shardingsphere#3115](https://github.com/apache/incubator-shardingsphere/issues/3115)

**Comment by dongzl** [comment]
Hi @KomachiSion ,  what need we do for PostgreSQL support, like MySQL parse binlog, or other?

**Comment by avalon566** [comment]
postgresql jdbc implement a logic replication interface,i think it's enough for us to realtime sync.

**Comment by avalon566** [comment]
@dongzl If you want to develop for PostgreSQL support, you can open a new issue to assign that work to yourself.

**Comment by dongzl** [comment]
> @dongzl If you want to develop for PostgreSQL support, you can open a new issue to assign that work to yourself.

Hi @avalon566 , OK, I'm glad to contribute to this work, I will read PostgreSQL JDBC document, then discuss with you about the work and do it.

**Comment by KomachiSion** [comment]
Prepare Work has already finish.
