### ISSUE TITLE
Compilation failure because unhandled exception

### ISSUE THREAD

**Issue by ssxlulu** [avalon566/sharding-scaling#26]
Some functions in class MySQLBinlogReader do not handler the interruptedException.

![image](https://user-images.githubusercontent.com/14773179/67548959-c27fe600-f735-11e9-9422-3fb38faa53a1.png)

**Comment by avalon566** [comment]
I forget to commit some files. I will fix it.

**Comment by ssxlulu** [comment]
> I forget to commit some files. I will fix it.

Ok, I want to test the migration function.
One question, how could I stop the process after migration?

**Comment by avalon566** [comment]
Ctrl+C! You need to manual check sync progress now.
