### ISSUE TITLE
Parse MySQL binlog event

### ISSUE THREAD

**Issue by KomachiSion** [avalon566/sharding-scaling#3]
For remove `mysql-binlog-connector-java jar` dependences and support MySQL real-time migrate, We need to dump and parse some important binlog events.

Following is require events I think:

- [x] ROTATE_EVENT
- [x] FORMAT_DESCRIPTION_EVENT
- [x] TABLE_MAP_EVENT
- [x] WRITE_ROWS_EVENTv2
- [x] UPDATE_ROWS_EVENTv2
- [x] DELETE_ROWS_EVENTv2
- [x] WRITE_ROWS_EVENTv1
- [x] UPDATE_ROWS_EVENTv1
- [x] DELETE_ROWS_EVENTv1
- [ ] WRITE_ROWS_EVENTv0
- [ ] UPDATE_ROWS_EVENTv0
- [ ] DELETE_ROWS_EVENTv0

Has any other events we need to parse?

**Comment by avalon566** [comment]
I have already finished ROTATE_EVENT,FORMAT_DESCRIPTION_EVENT,TABLE_MAP_EVENT,WRITE_ROWS_EVENTv2,UPDATE_ROWS_EVENTv2,DELETE_ROWS_EVENTv2

**Comment by SanmuWangZJU** [comment]
perhaps we can use canal to fetch mysql binlog events, which is fully functional and performs well

**Comment by avalon566** [comment]
yes,but this project will merge into shardingsphere,the code and dependency must comply with the apache foundation rule,so we decide to rewrite this component.

**Comment by KomachiSion** [comment]
@SanmuWangZJU, of course, canal is fully functional to fetch mysql binlog events.
But it is too heavy in dependency and function. Even we only use `dbsync` module.

**Comment by SanmuWangZJU** [comment]
ok, I understand~
Do you need more developer? I'd like to  participated in this development,
what should i do?

杨翊 Sion Yang <notifications@github.com> 于2019年9月27日周五 上午9:12写道：

**Comment by KomachiSion** [comment]
@SanmuWangZJU , Write/Update/Delete_rows_eventv0/1 also need to develop, but you need to discuss with @avalon566. Maybe he is working for it.

If you want to develop for other works, you can see #2 , and open a new issue to assign that work to yourself.

**Comment by KomachiSion** [comment]
Write/Update/Delete_rows_eventv0 is used in old mysql version, so we can ignore these events now
